
# CONFIGURAÇÕES DO DOCKER 

version: '3.9'

services: # quais serviços estamos utilizando
  database:
    image: postgres
    container_name: tutorial # define o nome do container
    restart: always
    ports: # porta de conexão do host e do contêiner
      - 5432:5432
    environment: # dados do ambiente
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local